services:
  postgres:
    image: postgres:15
    container_name: jobgem-postgres-db
    restart: always
    ports:
      - "5499:5432"
    environment:
      POSTGRES_USER: jobgemadmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobgem
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin_container
#    restart: always
#    ports:
#      - "8090:80"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@example.com
#      PGADMIN_DEFAULT_PASSWORD: password
#    depends_on:
#      - postgres
volumes:
  postgres_data: