### Request Access Token
POST {{signIn_endpoint}} HTTP/1.1
Content-Type: application/json

{
  "usernameOrEmail" : "{{usernameOrEmail}}",
  "password": "{{password}}"
}

> {% client.global.set("jobgem_access_token", response.body.accessToken); %}

### Update Job
PUT {{base_path_jobgem}}/api/v1/jobs/7
Content-Type: application/json
Authorization: Bearer {{jobgem_access_token}}

{
  "title": "Scala Software Engineer",
  "description": "We are looking for a talented software engineer..."
}
